linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_use_package_imports