name: default_themes
description: Application allow you switch certain themes.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true